version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
  build:
    commands:
      - echo "Building Docker Image"
      - docker build -t myapp .
      - echo "Running Container"
      - docker run myapp
